Name:           ros-indigo-surface-perception
Version:        1.0.1
Release:        0%{?dist}
Summary:        ROS surface_perception package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/surface_perception
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-pcl-conversions
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-rospy
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-tf
Requires:       ros-indigo-tf-conversions
Requires:       ros-indigo-visualization-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-pcl-conversions
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-tf-conversions
BuildRequires:  ros-indigo-visualization-msgs

%description
Simple library for segmentation of tabletop and shelf surfaces

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Mar 06 2018 Justin Huang <jstn@cs.washington.edu> - 1.0.1-0
- Autogenerated by Bloom

* Tue Feb 13 2018 Justin Huang <jstn@cs.washington.edu> - 1.0.0-0
- Autogenerated by Bloom

* Mon Aug 28 2017 Justin Huang <jstn@cs.washington.edu> - 0.2.1-0
- Autogenerated by Bloom

* Mon Aug 28 2017 Justin Huang <jstn@cs.washington.edu> - 0.2.0-0
- Autogenerated by Bloom

* Mon Jul 24 2017 Justin Huang <jstn@cs.washington.edu> - 0.1.3-0
- Autogenerated by Bloom

* Wed Jul 19 2017 Justin Huang <jstn@cs.washington.edu> - 0.1.2-0
- Autogenerated by Bloom

* Wed Jun 07 2017 Justin Huang <jstn@cs.washington.edu> - 0.1.1-0
- Autogenerated by Bloom

* Wed Jun 07 2017 Justin Huang <jstn@cs.washington.edu> - 0.1.0-0
- Autogenerated by Bloom

